### ISSUE TITLE
Add support for programmatically created Views

### ISSUE THREAD

**Issue by ataulm** [novoda/espresso-support#1]
https://github.com/novoda/spikes/pull/326

@BraisGabin I've moved the conversation here (just about to move the code to this repo).

Thanks for your PR and your patience.

I acknowledge the issue you're facing.

- I'd like to test whether using `afterActivityLaunched` has any other implications
- would prefer a separate rule to avoid the unused field/unused ctor parameter in `ViewTestRule`

**Comment by ataulm** [comment]
@braisGabin Please see: https://github.com/novoda/espresso-support/compare/abstract_view_creation

This approach uses a collaborator instead of an abstract method, and doesn't require you to pass an unused layout id.

For your case, it would read:

```java
@Rule
public ViewTestRule<UserScreen> viewTestRule = new ViewTestRule<>(new ViewCreator<UserScreen>() {
    @Override
    public UserScreen createView(Context context, ViewGroup parentView) {
        return UserScreen.createScreen(context, parentView, activityComponentMock);
    }
});
```

Let me know if this works for you; I'll open a PR for it for a proper review tomorrow.

**Comment by BraisGabin** [comment]
> I'd like to test whether using afterActivityLaunched has any other implications

I use this callback in this other library: https://github.com/21Buttons/FragmentTestRule and we don't have any issue so far.

I like the ViewCreator idea. Lambda rules!

**Comment by ataulm** [comment]
nice one, I'll open the PR shortly. Thanks for your help!
