### ISSUE TITLE
How to test <merge/> ?

### ISSUE THREAD

**Issue by Aetherna** [novoda/espresso-support#11]
Is there a way to tests views that are defined as <merge/>? (Im using those in view pager)

**Comment by ataulm** [comment]
For sure! Remember that the merge tags are essentially saying that the enclosed elements are going to placed in a single ViewGroup - without a ViewGroup to contain them, they are not able to be inflated.

Consider the following:

```xml
<merge>
    <TextView .../>
    <TextView .../>
</merge>
```

You'd have to have a second file (unless that was your activity layout XML - which gets merged into a single FrameLayout):

```xml
<LinearLayout
    android:orientation="vertical"
    ... />

    <include layout="@layout/name_of_file_with_merge_tags" />
</LinearLayout>
```

Then use the second file as the layout for your ViewTestRule which in this case would be `ViewTestRule<LinearLayout>`.

**Comment by ataulm** [comment]
Note however, we don't usually test such files. If a layout has `merge` tags, we're usually inflating them programmatically into a custom view:

```java
class MyCustomView extends LinearLayout {
    ...
    @Override
    public void onFinishInflate() {
        super.onFinishInflate();
        View.inflate(getContext(), R.layout.name_of_file_with_merge_tags, this);
    }
}
```

and creating another layout to inflate MyCustomView:

```xml
<com.example.MyCustomView
    ... />
```

and using that as the layout for the `ViewTestRule<MyCustomView>`. This ensures we're testing the view as a whole as we would use it in the app. We rarely, if ever, share `merge` layouts between multiple Views, and I never use XML based includes, preferring custom views for encapsulation and clarity.

**Comment by ataulm** [comment]
Feel free to reopen if you have further questions.
