### ISSUE TITLE
Allow to launch the view later

### ISSUE THREAD

**Issue by BraisGabin** [novoda/espresso-support#12]
Some of my views have values that I set in construction time. I need to test how my View behaves with different values. Right now I need to have a class per each value.

A boolean in the constructor would be nice to allow this behaviour. Something similar to `launchActivity` in `ActivityTestRule`.

**Comment by ataulm** [comment]
Hi Brais, this is also likely not to be supported. I expect that the majority of users of this library will only be using XML-inflated views, and a minority creating programmatically. The `ViewTestRule` allows both, and allows testing in the way you need above with the trade-off that you need to create a separate test class per set of values.

I'd recommend:

- pulling out any logic that causes your view to change _behaviour_ based on ctor params and test that separately.
- Is there a discrete, finite set of values you allow? Sounds like it could be a good candidate for different Views.
- Else are you testing boundary values? Would use a separate test class for each of these, `ViewCreator` should allow you to instantiate the views with whatever values you need. 
- extending/copying `ViewTestRule` in your own project for this.
