### ISSUE TITLE
Was this library unpublished from JCenter?

### ISSUE THREAD

**Issue by jkaan** [novoda/espresso-support#24]
Suddenly noticed that our builds were failing because we couldn't get this library anymore, so was wondering if this was the case :).

**Comment by ataulm** [comment]
Not AFAIK. @mecharyry can you check please? 🙏

**Comment by jkaan** [comment]
Woah that was the fastest response I've ever got. Really awesome!

For now we just switched to this repository: https://dl.bintray.com/novoda/maven/, don't think it matters a whole lot.

**Comment by tasomaniac** [comment]
Could it be because of a potential outage of jcenter?

**Comment by MechaRyRy** [comment]
According to our `Bintray` account it is linked in JCenter. However when I try to use it in a project it is not found. Checking `JCenter` from https://bintray.com/beta/#/bintray/jcenter?tab=packages and it is not present. We'll have to get in contact with them to see what has gone wrong. This seems like an unfortunate consequence of an account migration. 

Thanks @ataulm for the ping 👅

**Comment by mr-archano** [comment]
@jkaan this seems to be a side-effect of the account migration that @mecharyry mentioned. I will take a look tomorrow morning and post here any update.

**Comment by jkaan** [comment]
@mr-archano Do you have an update ? :)

**Comment by mr-archano** [comment]
JCenter seems ok again:
- https://jcenter.bintray.com/com/novoda/espresso-support/
- https://jcenter.bintray.com/com/novoda/espresso-support-extras/

@jkaan you should be able to sync up your project just fine now (and remove the additional buildscript repo altogether)

**Comment by astr0-4** [comment]
I was experiencing the same issue. Everything is working fine now. 👍

**Comment by jkaan** [comment]
@mr-archano Yes, it's working again indeed! Thanks :)
