### ISSUE TITLE
Update activity attribute to Android 12

### ISSUE THREAD

**Issue by jonnycaley** [novoda/espresso-support#26]
To be able to target android 12 all activities that use intent-filters must declare the `android:exported` attribute, [reference here](https://developer.android.com/about/versions/12/behavior-changes-12#exported).

When trying to build an app that depends on espresso-support on android 12 I got the following error:

> Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl779923006.tmp/base.apk (at Binary XML file line #472): com.novoda.espresso.TalkBackStateSettingActivity: Targeting S+ (version 10000 and above) requires that an explicit value for android:exported be defined when intent filters are present]

I would make a PR myself but I cannot find the `TalkBackStateSettingActivity` file in the repository 🤔 The only place I have found reference to it is in [this repository](https://github.com/21Buttons/view-rule). Should it be addressed there instead?

**Comment by ataulm** [comment]
It's probably in novoda/accessibilitools but I'm not sure who looks after these repos anymore

**Comment by ataulm** [comment]
It's this now, I don't know if this version has been released 

https://github.com/novoda/espresso-support/blob/master/extras/src/main/java/com/novoda/espresso/AccessibilityServiceTogglingActivity.java

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
