### ISSUE TITLE
Allow to launch the View in any Activity you want

### ISSUE THREAD

**Issue by BraisGabin** [novoda/espresso-support#9]
This can be usefull to test views with `design` views. They need to be created with `Theme.AppCompat`.

And, not ideal, but some views can have dependencies with it's Activity. For example, the Activity implements a Listener.

**Comment by ataulm** [comment]
Can you give an example?

The aim of the `ViewTestRule` is to test your Views in isolation - if your views are coupled to your activities by means of casting `view.getContext()` to bind the activity as a listener, then this is not likely to be supported with this library.

At that point, you could use `ActivityTestRule`?

**Comment by BraisGabin** [comment]
- I need a `FragmentActivity` to launch a v4 `FragmentDialog` inside my View.
- In my use case my view needs to launch a Dialog. I use a `FragmentDialog` to persist the dialog state. The only way to receive the events from the Dialog to my screen is using the activity. I force that the `Activity` that launchs that `FragmentDialog` must implmement `FooListener`. If it doesn't impelement it, huge crash.
- [Flow](https://github.com/square/flow), you need an specific context to use it. If you are using Flow you are implementing lots of views. It's very likely that you are going to use this library too.

**Comment by ataulm** [comment]
The ViewTestRule is intended to test a single view, in isolation: simple callbacks or things that the view itself can control.

- How does your view create and show the dialog?
- Is it responsible for creating the fragment and handling any callbacks/events from the dialog?

These questions are to help me determine whether I'm missing something about a common use case or whether your view/dialog is architechted in a niche way.

**Comment by ataulm** [comment]
>The only way to receive the events from the Dialog to my screen is using the activity. 

This suggests you need the standard activity test rule.

The ViewTestRule is to test a single view - so in our cases, we'd either have the View manage the dialog state itself (or not handle dialog state) _or_ use the ViewTestRule just to assert the "show dialog" callback was fired, and something else would be responsible for the dialog itself.

**Comment by ataulm** [comment]
Feel free to open this again to continue the discussion.

**Comment by BraisGabin** [comment]
> Is it responsible for creating the fragment and handling any callbacks/events from the dialog?

I can create a Dialog Factory and inject it. But I feel it's a bit overkill for a simple confirmation dialog.

Use case: the user clicks a button to delete, the view shows a confirmation dialog, the user confirms/cancels and the view notify to the presenter (or does nothing).

But, sure, I could split that in different and smaller tests.

I understand your concern about the library focus so we can keep this closed.
